Repository cargo-generate/cargo-generate, pull requests merged in 2018-10, with the labels that each got.

#84 Issue/65
  src/main.rs
  src/projectname.rs
Labels: changes requested, needs rebase

#98 Safety check
  src/ignoreme.rs
  tests/integration/basics.rs
Labels: needs review

#103 fix(test): paths are hard mk
  tests/integration/basics.rs
Labels: needs review

#109 fixed some clippy warnings
  src/git.rs
  src/ignoreme.rs
Labels: needs cargo fmt

#111 feat(releases): travis deploy releases
  .travis.yml
  Cargo.lock
  Cargo.toml
Labels: needs review

#101 0.2.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: release
