Repository cargo-generate/cargo-generate, pull requests merged in 2018-12, with the labels that each got.

#137 0.2.2
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: needs review

#139 chore: Update liquid
  Cargo.lock
  Cargo.toml
  src/template.rs
Labels: chore, needs cargo fmt

#115 new shallow main
  src/bin/client.rs
  src/lib.rs
Labels: waiting on response

#141 TEMPLATES.md: add procmacro-quickstart template
  TEMPLATES.md
Labels: changes requested
