Repository cargo-generate/cargo-generate, pull requests merged in 2019-08, with the labels that each got.

#157 Fix assert! macro usage
  tests/integration/basics.rs
Labels: current release, needs review

#175 nits
  src/template.rs
  tests/integration/basics.rs
  tests/integration/helpers/project_builder.rs
Labels: current release, needs review

#166 Respect branch name from template
  src/git.rs
  src/lib.rs
  tests/integration/basics.rs
Labels: current release

#178 Update README.md with latest install instructions
  README.md
Labels: changes requested, current release

#161 Added new feature: filename can contains template tag(s)
  README.md
  src/template.rs
  tests/integration/basics.rs
Labels: current release, needs rebase

#174 Feature: Add file for configuring include / exclude of files to template
  Cargo.lock
  Cargo.toml
  README.md
  src/config.rs
  src/ignoreme.rs
  src/include_exclude.rs
  src/lib.rs
  src/template.rs
  tests/integration/basics.rs
Labels: current release, needs review

#179 Fix: Only try to remove files that exist
  src/ignoreme.rs
  tests/integration/basics.rs
Labels: needs review
