Repository cargo-generate/cargo-generate, pull requests merged in 2020-09, with the labels that each got.

#241 Use default remote branch instead of `master`
  src/git.rs
  src/lib.rs
  tests/integration/basics.rs
  tests/integration/helpers/project_builder.rs
Labels: waiting for extra reviews

#242 Support abbreviated `owner/repo` Git URL format
  src/git.rs
  src/lib.rs
  tests/integration/basics.rs
Labels: waiting for extra reviews

#237 Update the project to the latest world version
  .travis.yml
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  src/authors.rs
  src/config.rs
  src/emoji.rs
  src/git.rs
  src/ignoreme.rs
  src/include_exclude.rs
  src/interactive.rs
  src/lib.rs
  src/main.rs
  src/progressbar.rs
  src/projectname.rs
  src/template.rs
  tests/integration/basics.rs
Labels: decision needed, waiting for extra reviews

#246 🕴️ 0.5.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: release
